//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_FIREBALL                    130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_DOWN                        158
#define IDB_LEFT                        159
#define IDB_RIGHT                       164
#define IDB_UP                          165
#define IDB_BACKGROUND1                 166
#define IDB_BACKGROUND0                 167
#define IDB_BACKGROUND2                 168
#define IDB_BITMAP4                     169
#define IDB_BACKGROUND3                 169
#define IDB_SLIME1                      177
#define IDB_SLIME2                      178
#define IDB_SLIME3                      179
#define IDB_SLIMEJUMP1                  180
#define IDB_SLIMEJUMP2                  181
#define IDB_SLIMEJUMP3                  182
#define IDB_SLIMEJUMP4                  183
#define IDB_SLIMEJUMP5                  184
#define IDB_SLIME_HIT                   189
#define IDI_ICON1                       190
#define IDB_MOVEDOWN0                   191
#define IDB_MOVEDOWN1                   192
#define IDB_MOVEDOWN2                   193
#define IDB_MOVEDOWN3                   194
#define IDB_MOVEDOWN4                   195
#define IDB_MOVELEFT0                   196
#define IDB_MOVELEFT1                   197
#define IDB_MOVELEFT2                   198
#define IDB_MOVELEFT3                   199
#define IDB_MOVELEFT4                   200
#define IDB_MOVELEFT5                   201
#define IDB_MOVERIGHT0                  202
#define IDB_MOVERIGHT1                  203
#define IDB_MOVERIGHT2                  204
#define IDB_MOVERIGHT3                  205
#define IDB_MOVERIGHT4                  206
#define IDB_MOVERIGHT5                  207
#define IDB_MOVEUP0                     208
#define IDB_MOVEUP1                     209
#define IDB_MOVEUP2                     210
#define IDB_MOVEUP3                     211
#define IDB_MOVEUP4                     212
#define IDB_DOWN_HIT0                   213
#define IDB_DOWN_HIT1                   214
#define IDB_DOWN_HIT2                   215
#define IDB_RIGHT_HIT0                  216
#define IDB_RIGHT_HIT1                  217
#define IDB_RIGHT_HIT2                  218
#define IDB_LEFT_HIT0                   219
#define IDB_LEFT_HIT1                   220
#define IDB_LEFT_HIT2                   221
#define IDB_UP_HIT0                     222
#define IDB_UP_HIT1                     223
#define IDB_UP_HIT2                     224
#define IDB_GAMESTART                   225
#define IDB_PAUSE                       226
#define IDB_HELPBAR                     227
#define IDB_ENDMUSIC                    228
#define IDB_EMPTY_HEART                 229
#define IDB_BITMAP5                     230
#define IDB_HEART                       230
#define IDB_STORE                       233
#define IDB_hill                        235
#define IDB_aman                        236
#define IDB_stone1                      237
#define IDB_stone2                      238
#define IDB_stone3                      239
#define IDB_bigbox                      240
#define IDB_cpot                        241
#define IDB_arrowright                  242
#define IDB_arrowleft                   243
#define IDB_pottree                     245
#define IDB_tree                        246
#define IDB_BITMAP3                     247
#define IDB_candle                      247
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
